<a href="https://colab.research.google.com/github/Muhirwakyeyune/improvedonline/blob/master/Group3_B23FinalProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [709]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [710]:
# Get Data: Do not touch it.
def get_data():
  data_url = "http://lib.stat.cmu.edu/datasets/boston"
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
  X = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
  y = raw_df.values[1::2, 2]
  return X,y

In [756]:
# cgs
def cgs(A):
  """
    Q,R = cgs(A)
    Apply classical Gram-Schmidt to mxn rectangular/square matrix. 

    Parameters
    -------
    A: mxn rectangular/square matrix   

    Returns
    -------
    Q: mxn square matrix
    R: nxn upper triangular matrix

  """
  # ADD YOUR CODES
  m,n= A.shape # get the number of rows of A
  # get the number of columns of A

  R= np.zeros((n,n)) # create a zero matrix of nxn
  Q= np.ones((m,n)) # copy A (deep copy)
  for k  in range(n):
    w = A[:,k]
    
    for j in range(k-1):
      R[j,k]=np.dot(np.transpose(Q[:,j]),w)
    for j in range(k-1):
      w = w - np.dot(R[j,k],Q[:,j])
    R[k,k]= np.linalg.norm(w, ord=2)
    #print(w/R[k,k])
    Q[:,k] = w/ R[k,k]
    #print (R[:,k])
  return Q,R
  


In [757]:
A = np. array([[1,2,4],[0,0,5],[0,3,6]])

In [758]:
R

array([[1.        , 0.        , 4.        ],
       [0.        , 3.60555128, 0.        ],
       [0.        , 0.        , 7.81024968]])

In [759]:
np.dot(Q,R)

array([[1., 2., 4.],
       [0., 0., 5.],
       [0., 3., 6.]])

In [760]:
# Implement BACK SUBS
def backsubs(U, b):

  """
  x = backsubs(U, b)
  Apply back substitution for the square upper triangular system Ux=b. 

  Parameters
  -------
    U: nxn square upper triangular array
    b: n array
    

  Returns
  -------
    x: n array
  """

  n= U.shape[1]
  x= np.zeros((n,))
  b_copy= np.copy(b)

  if U[n-1,n-1]==0.0:
    if b[n-1] != 0.0:
      print("System has no solution.")
  
  else:
    x[n-1]= b_copy[n-1]/U[n-1,n-1]
  for i in range(n-2,-1,-1):
    if U[i,i]==0.0:
      if b[i]!= 0.0:
        print("System has no solution.")
    else:
      for j in range(i,n):
        b_copy[i] -=U[i,j]*x[j]
      x[i]= b_copy[i]/U[i,i]
  return x

In [761]:
# Add ones
def add_ones(X):

  # ADD YOUR CODES
  m,n = X.shape
  New_X = np.ones((m,n+1))
  New_X[:m,1:n+1]= X
  return New_X


In [762]:
X,y = get_data()
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [763]:
X= add_ones(X)

In [764]:
def split_data(X,Y, train_size):
  # ADD YOUR CODES
  # shuffle the data before splitting it
  train_size =int(train_size*len(Y))
  m,n = X.shape
  X_Y = np.zeros((m,n+1))
  Y=Y.reshape(len(Y),1)
  X_Y=np.concatenate((X, Y), axis=1)
  np.random.shuffle(X_Y)
  x_train = X_Y[:train_size,:-1]
  y_train  = X_Y[:train_size,-1]
  x_test = X_Y[train_size:,:-1]
  y_test = X_Y[train_size:,-1]
  return  x_train, y_train, x_test, y_test
  



In [765]:
X_train, Y_train, X_test, Y_test = split_data(X,y,0.8)

In [766]:
def mse(y, y_pred):
    # ADD YOUR CODES
    error = np.subtract(y,y_pred)**2
    return np.mean(error)

In [767]:
def normalEquation(X,y):
    # ADD YOUR CODES
  Theta = np.linalg.inv(X.T@X)@X.T@y
  return Theta

In [781]:
class LinearRegression:

  def __init__(self, arg):
      # ADD YOUR CODES
      self.arg = arg
      self.theta = None

  def fit(self,x,y):
      # ADD YOUR CODES
      if self.arg == "cgs":
        Q,R =cgs(x)
        y = Q.T@y
        self.theta = backsubs(R,y)
      elif self.arg == "NormalEq":
        self.theta = normalEquation(x,y)
    
  def predict(self,x):
      #ADD YOUR CODE\
      y_pred = x@self.theta
      return y_pred


In [782]:
# Instanciate the LinearRegression class 
model= LinearRegression("NormalEq")

In [783]:
# Train the model
model.fit(X_train,Y_train)

In [784]:
# print the learned theta
model.theta

array([ 3.83770484e+01, -4.78205124e-02,  4.49723381e-02,  1.83976495e-02,
        3.08891765e+00, -2.00410290e+01,  3.61286574e+00,  5.38487655e-03,
       -1.59754882e+00,  2.53555084e-01, -9.98697474e-03, -9.56251935e-01,
        1.12633688e-02, -5.67955118e-01])

In [785]:
# Make a prediction on X_test
y_pred = model.predict(X_test)

In [786]:
# Compute the MSE (Evaluate both, regression and classification)
mse(Y_test,y_pred)

17.947694069056933

In [787]:
# Instanciate the LinearRegression class 
model= LinearRegression("cgs")

In [788]:
# Train the model
model.fit(X_train,Y_train)

In [789]:
# print the learned theta
model.theta

array([ 2.04600541e+02,  1.52965599e+01, -1.07013126e-01, -6.82360762e+00,
       -2.10736910e+00, -6.98087511e+01, -4.44680419e+00, -2.09764211e-01,
       -2.30834962e+00, -4.31045950e-01, -9.24534459e-03, -1.78001512e-01,
       -7.90298561e-03, -1.56472666e-01])

In [790]:
# Make a prediction on X_test
y_pred = model.predict(X_test)

In [791]:
mse(Y_test,y_pred)

45642.47857334511